# Generated by Django 5.1.6 on 2025-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='tg_id',
            field=models.CharField(default='blank_id', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='tg_id',
            field=models.CharField(default='blank_id', max_length=255),
        ),
    ]
